version: "3"

services:
  zookeeper:
    logging:
      driver: none
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-network
  kafka:
    logging:
      driver: none
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
      
  mongo-api:
    restart: on-failure:10
    depends_on:
      - kafka
    build:
      context: ./.
      dockerfile: ./mongoAPIServer/Dockerfile
    ports:
      - 8123:8123
    environment:
      KAFKA_URI: kafka:9092
    networks:
      - kafka-network
    # extra_hosts:
    #  - "host.docker.internal:host-gateway"
networks:
  kafka-network:
    driver: bridge